config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/debug_session'

  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'

  post 'payments/create'

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }

  after_create_commit { CommentUpdateJob.perform_later(self, self.user) }

  # Called by e.g. <%= @product.comments.rating_desc.first %>
  scope :rating_desc, -> { order(rating: :desc) }
  # Called by e.g. <%= @product.comments.rating_asc.first %>
  scope :rating_asc, -> { order(rating: :asc) }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user

    respond_to do |format|
      if @comment.save
        # ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        # ProductChannel.broadcast_to @product.id, comment: @comment, average_rating: @product.average_rating

        # ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment}), average_rating: @product.average_rating

        # ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment, current_user: current_user}), average_rating: @product.average_rating

        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <%= comment.user.first_name %>
    <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if (current_user && (current_user.admin? || (current_user.id == comment.user_id))) %>
      <%= link_to ('<span class="comment-delete glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

app/views/comments/create.js.erb
$("#new_comment").html("<h3>Quack!</h3>");
// $('#product-reviews').prepend("<%= j render @comment %>");
// $("#average_rating_outside_div").html('<p><div class="rated" data-score=<%= @product.average_rating %>></div></p>');
// refreshRating();