config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/debug_session'

  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'

  post 'payments/create'

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
  
end

app/views/shared/_footer.html.erb
<footer>
  <p id="footer_text">&copy; 2018 Ruben Verstraten</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <h1>
    Rubber Duck Debug
  </h1>
</header>

app/views/shared/_nav.html.erb
<nav>
  <div id="centerDiv">
    <ul class="centerUL">
      <li>
        <!-- < % = link_to image_tag("favicon.png",
        id: "icon_navbar",
        class: "img-responsive",
        alt: "Icon"), root_path % > -->
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span>
        <% end %>
      </li>
      <!-- <li><%= link_to "About", simple_pages_about_path %></li> -->
      <li>
        <!-- < % = link_to "Ducks", products_path % > -->
        <%= link_to image_tag("duck_icon.png",
          id: "duck_navbar",
          class: "img-responsive",
          alt: "Icon"), products_path %></li>
      </li>
      <% if (signed_in? && current_user.admin?) %>
        <li>
          <%= link_to orders_path do %>
            <span class="glyphicon glyphicon-comment"></span>
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to simple_pages_contact_path do %>
          <span class="glyphicon glyphicon-envelope"></span>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to users_path do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </li>
      <% end %>
      <li>
      <% if user_signed_in? %>
        <!-- < % = link_to('Logout', destroy_user_session_path, method: :delete) % > -->
        <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-log-out"></span>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in"></span>
        <% end %>
      <% end %>
      </li>
      <!-- <li> -->
        <!-- < % = link_to '' do % > -->
          <!-- <span class="glyphicon glyphicon-refresh"></span> -->
          <!-- <span class="glyphicon glyphicon-menu-hamburger"></span> -->
        <!-- < % end % > -->
      <!-- </li> -->
    </ul>
  </div>
</nav>

<!-- <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul>
        <li><%= link_to image_tag("favicon.png",
          id: "icon_navbar",
          class: "img-responsive",
          alt: "Icon"), root_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
        <li><%= link_to "Ducks", products_path %></li>
        <li><%= link_to "Chats", orders_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav> -->

<!-- <ul class="nav pull-right">
  <li>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
  <% end %>
  </li>
</ul> -->

app/views/shared/_stripe_checkout_button.html.erb
<!-- https://stripe.com/docs/checkout -->

<script
  id="stripe_checkout_button_id"
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="<%= asset_path(@product.image_url) %>"
  data-name="Rubber Duck Debug"
  data-description="Session with duck '<%= @product.name %>'"
  data-amount="<%= @product.price*100.to_i %>"
  data-currency="eur">
</script>

<!-- data-image="<%= asset_path("favicon.png") %>" -->