config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/debug_session'

  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'

  post 'payments/create'

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  validates :name, presence: true
  
  def self.search(search_term)
    if Rails.env.development?
      # Dev Mode (sqlite3)
      Product.where("name LIKE ?", "%#{search_term}%")
    else
      # Production or test mode (PostgreSQL)
      Product.where("name ilike ?", "%#{search_term}%")
    end
  end

  # Called by <%= @product.highest_rating_comment %>
  def highest_rating_comment
    comments.rating_desc.first
  end

  # Called by <%= @product.lowest_rating_comment %>
  def lowest_rating_comment
    comments.rating_desc.last
  end

  # Called by <%= @product.average_rating %>
  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Everyone can see the products (index), but only some can modify
  before_action :authenticate_user!, :except => [:index]

  # The master layout for all product pages can be specified here.
  # To specify different master layouts for the pages:
  # 'render layout ""' within dev for the pages...
  layout "products"
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      # Search was defined in the model file 'product.rb':
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # redirect_back(fallback_location: root_path)
    # Info about will_paginate : https://www.youtube.com/watch?v=MIf1ojX2AGY
    @comments = @product.comments.order("created_at DESC").page(params[:page]).per_page(3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :colour, :price, :image_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div id="product-reviews">

  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>

  <hr>

  <!-- Info about will_paginate: https://www.youtube.com/watch?v=MIf1ojX2AGY -->
  <%= will_paginate @comments %>

</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">

    <div class="field form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: "products_form_name", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: "products_form_description", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :colour %>
      <%= form.text_field :colour, id: "products_form_color", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :price %>
      <%= form.text_field :price, id: "products_form_price", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, id: "products_form_image_url", class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-default" %>
    </div>

  </div> <!-- / Container Fluid -->

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>

  <div id="add_review_div_around">

    <!-- <h4>Add a review:</h4> -->
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <!-- <p> -->
      <!-- < % = f.label :body, "Add a quack for \"#{@product.name}\"", id: "review_label" % > -->
    <!-- </p> -->
    <p>
      <%= f.text_area :body, id:"showproduct_newcommentbody", class: "form-control" %>
    </p>

    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Quack", class: "btn btn-default" %>
    </p>
    <% end %>

  </div> <!-- / id="add_review_txtbox" -->

<% end %>

app/views/products/_product.html.erb
<!-- Loop the products html into the webpage -->
<!-- < % @products.each do |product| % > -->

<% cache product do %>

  <div class="col-xs-12 col-sm-4 col-md-3">
    <div class="product_aspect_ratio_outer_2">
      <div class="product_aspect_ratio_inner_2">
        <%= image_tag(product.image_url,
          class: "img-responsive product_image_2",
          alt: product.image_url )
        %>
        <h3>
          <%= product.name %>
        </h3>
        <p>
          <%= product.description    %>
        </p>
        <p>
          <%= number_to_currency(product.price, unit: "€") + " (30min.)" %>
        </p>
        <p>
          <% if (signed_in? && current_user.admin?) %>
            <%= link_to 'Show', product %>
            <%= link_to 'Edit', edit_product_path(product) %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <% if signed_in? %>
              <%= link_to 'Book', simple_pages_debug_session_path(id: product.id) %>
            <% end %>
            <%= link_to 'Show', product %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%= javascript_include_tag 'alert_fade.js' %>

<% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="notice" class="alert alert-info"><%= alert %></p>
<% end %>

<h1>Editing Duck</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

<div class="product-edit-bottom-spacing"></div>

app/views/products/index.html.erb
<%= javascript_include_tag 'alert_fade.js' %>

<% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="notice" class="alert alert-info"><%= alert %></p>
<% end %>

<!-- < % = @test_variable % > -->
<h1>Rubber Ducks</h1>

<%= form_with(id: 'product_search_form', url: products_path, method: 'get', local: true) do |form| %>
  <!-- < % = form.label :q, 'Search for:' % > -->
  <div class="container-fluid">
    <div class="form-group">
      <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control product_search_field', placeholder: 'Duck Name' %>
      <!-- < % = form.submit 'Search', id: 'product_search_btn', class: 'btn btn-default'  % > -->
      <%= button_tag(type: "submit", class: "btn btn-default", id: "product_search_btn") do %>
        <span class="glyphicon glyphicon-search"></span>
      <% end %>
    </div>
  </div>
<% end %>

<!-- ############################################################### -->
<!-- ############################################################### -->
<!-- ############################################################### -->

<% if (signed_in? && current_user.admin?) %>
  <%= link_to 'New Duck', new_product_path %>
<% else %>
  <!-- <br> -->
<% end %>

<!-- Responsive row -->
<div id="product_index_show" class="container-fluid">
  <div class="row">

    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>

  </div> <!-- / row -->
</div> <!-- / container-fluid -->

<% if (signed_in? && current_user.admin?) %>
  <%= link_to 'New Duck', new_product_path %>
  <br><br><br>
<% end %>

<br>
<!-- <div class="product-main-bottom-spacing"></div> -->

app/views/products/new.html.erb
<%= javascript_include_tag 'alert_fade.js' %>

<% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="notice" class="alert alert-info"><%= alert %></p>
<% end %>

<h1>New Duck</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

<div class="product-new-bottom-spacing"></div>

app/views/products/show.html.erb
<%= javascript_include_tag 'alert_fade.js' %>

<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

<% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="notice" class="alert alert-info"><%= alert %></p>
<% end %>

<% cache @product do %>

  <div class="content_width_wrapper" data-product-id="<%= @product.id %>">

    <h1 id="product_show_title"><%= @product.name %></h1>
    <p id="product_show_description"><span class="text-overflow"><%= @product.description %></span></p>

    <div id="product_show_page_show">
      <div class="product_show_page_asp_ratio_outer">
        <div class="product_show_page_asp_ratio_inner">
          <div class="product_show_page_image">
            <p>
              <%= image_tag(@product.image_url,
                id: "zoom_product_showpage",
                class: "img-responsive product_show_page_image img-zoom",
                alt: @product.image_url)
              %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- <p>Average Rating: <div class="rated" data-score="< % = @product.average_rating % >"></div> </p> -->
    <div id="average_rating_outside_div">
      <p><div class="rated" data-score="<%= @product.average_rating %>"></div></p>
    </div>

    <p>
      <!-- <strong>Price:</strong> -->
      <span id="product_show_price" class="text-overflow"><%= number_to_currency(@product.price, unit: "€") + " (30min.)" %></span>
    </p>

    <% if (signed_in? && current_user.admin?) %>
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'Back', products_path %>
    <% else %>
      <%= link_to 'Book', simple_pages_debug_session_path(id: @product.id) %> |
      <%= link_to 'Back', products_path %>
      <div style='padding-top:10px'></div>
      <!-- Stripe payments button -->
      <%= form_with(url: '/payments/create') do |form| %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <%= hidden_field_tag(:product_id, @product.id) %>
      <% end %>
    <% end %>

    <div class="product-show-bottom-spacing"></div>

    <%= render 'new_comment' %>

    <div class="product-show-bottom-spacing"></div>

    <%= render 'comments' %>

    <div class="product-show-bottom-spacing"></div>

  </div>

<% end %> <!-- / @product Cache -->